{"name": "Проверяем что невозможно авторизоваться незарегистрированным курьером. Возвращается сообщение об ошибке, статус ответа 404", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "('unregistered_login',)"}, {"name": "password", "value": "'unregistered_password'"}], "start": 1733843405455, "stop": 1733843405643}], "start": 1733843405455, "stop": 1733843405644, "uuid": "19e3188a-b580-48a1-a8ad-6dcefc1f5b58", "historyId": "6cb19586f891024ed482494cd1d2fdff", "testCaseId": "6cb19586f891024ed482494cd1d2fdff", "fullName": "tests.couriers.test_login_courier.TestLoginCourier#test_login_with_unregistered_courier", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-4B15D1P"}, {"name": "thread", "value": "8004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_login_courier"}]}